.catalog:
  name: "ADOP"
  version: "v0.1.0-rancher1"
  description: "Accenture DevOps Platform"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "TARGET_HOST"
      label: "Host IP"
      description: "Target host ip address"
      type: "string"
      required: true

    - variable: "LOGSTASH_HOST"
      label: "Logstash IP"
      description: "Logstash host ip address"
      type: "string"
      required: true

    - variable: "CUSTOM_NETWORK_NAME"
      label: "ADOP network"
      description: "ADOP network name"
      type: "string"
      default: "managed"
      required: true

    - variable: "LDAP_PWD"
      label: ""
      description: ""
      type: "password"
      default: "Jpk66g63ZifGYIcShSGM"
      required: true

    - variable: "LDAP_DOMAIN"
      label: ""
      description: ""
      type: "string"
      default: "ldap.example.com"
      required: true

    - variable: "LDAP_FULL_DOMAIN"
      label: ""
      description: ""
      type: "string"
      default: "dc=ldap,dc=example,dc=com"
      required: true

    - variable: "GERRIT_MYSQL_USER"
      label: ""
      description: ""
      type: "string"
      default: "gerrit"
      required: true

    - variable: "GERRIT_MYSQL_PASSWORD"
      label: ""
      description: ""
      type: "password"
      default: "gerrit"
      required: true

    - variable: "GERRIT_MYSQL_DATABASE"
      label: ""
      description: ""
      type: "string"
      default: "gerrit"
      required: true

    - variable: "GERRIT_USER_NAME"
      label: ""
      description: ""
      type: "string"
      default: "Gerrit Code Review"
      required: true

    - variable: "GERRIT_USER_EMAIL"
      label: ""
      description: ""
      type: "string"
      default: "gerrit@adop"
      required: true

    - variable: "SONAR_MYSQL_USER"
      label: ""
      description: ""
      type: "string"
      default: "sonar"
      required: true

    - variable: "SONAR_MYSQL_PASSWORD"
      label: ""
      description: ""
      type: "password"
      default: "sonar"
      required: true

    - variable: "SONAR_MYSQL_DATABASE"
      label: ""
      description: ""
      type: "string"
      default: "sonar"
      required: true

    - variable: "SONAR_ACCOUNT_LOGIN"
      label: ""
      description: ""
      type: "string"
      default: "jenkins"
      required: true

    - variable: "SONAR_ACCOUNT_PASSWORD"
      label: ""
      description: "Sonar account password"
      type: "password"
      default: "jenkins"
      required: true

    - variable: "SONAR_DB_LOGIN"
      label: ""
      description: ""
      type: "string"
      default: "sonar"
      required: true

    - variable: "SONAR_DB_PASSWORD"
      label: ""
      description: ""
      type: "password"
      default: "sonar"
      required: true

    - variable: "DOCKER_HOST"
      label: ""
      description: ""
      type: "string"
      default: ""

    - variable: "DOCKER_TLS_VERIFY"
      label: ""
      description: ""
      type: "string"
      default: ""

    - variable: "DOCKER_CLIENT_CERT_PATH"
      label: ""
      description: ""
      type: "string"
      default: "/root/.docker/"
      required: true

proxy:
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

jenkins:
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

nexus:
  health_check:
    port: 8081
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

gerrit:
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
